name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.config.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Windows VS2019, os: windows-2019 }
          - { name: Windows VS2022, os: windows-2022 }
          # Waiting for std library support of std::format
          #- { name: Linux GCC, os: ubuntu-20.04 }
          #- {
          #    name: Linux Clang,
          #    os: ubuntu-20.04,
          #    flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++,
          #  }
          #- { name: MacOS XCode, os: macos-11 }

    steps:
      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libxrandr-dev libxcursor-dev libudev-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev

      - name: Fractal - Checkout Code
        uses: actions/checkout@v2

      - name: SFML - Checkout Code
        uses: actions/checkout@v2
        with:
          repository: SFML/SFML
          path: SFML
          ref: 2.6.x

      - name: SFML - Configure CMake
        shell: bash
        run: cmake -S $GITHUB_WORKSPACE/SFML -B $GITHUB_WORKSPACE/SFML/build -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/SFML/install -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_SHARED_LIBS=ON ${{matrix.platform.flags}}

      - name: SFML - Build
        shell: bash
        run: cmake --build $GITHUB_WORKSPACE/SFML/build --config Release --target install

      - name: Fractal - Configure CMake
        shell: bash
        run: cmake -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/install -DCMAKE_VERBOSE_MAKEFILE=ON -DSFML_DIR=$GITHUB_WORKSPACE/SFML/install/lib/cmake/SFML -DFRACTAL_STATIC_LINKING=OFF ${{matrix.platform.flags}}

      - name: Fractal - Build
        shell: bash
        run: cmake --build $GITHUB_WORKSPACE/build --config Release --target install
